version: '3'
services:
  db:
    image: postgis/postgis:11-3.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: postgis_adapter_test
      POSTGRES_PASSWORD: postgres
